<a href="https://colab.research.google.com/github/LiuChen-5749342/Generative-AI-and-AI-Applications/blob/main/Task_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Required Task 15**
(check the python notebook RAG_5_Multimodal_Chunking_OpenSourced.ipynb
for context and further details)

Fine-tune based on the data 'credit_card_aa.csv'. The data is also available at https://huggingface.co/datasets/priyaannamani/credit_card_qa

Create two fine-tuned models. The first one should take complaint as the input and predict policy_category. The second should take complaint as the input and predict resolution.

Take a sample of 60 records to fine-tune and evaluate the fine-tuned models on all the records in the dataset.

You can use either or both distilbert_base_uncased and distilgpt2 models. Performance comparative analysis of how well fine-tuning works.

Write a short narrative at the end to discuss your insights from fine-tuning.

# Install necessary libraries

In [1]:
!pip install transformers datasets
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, Trainer
from datasets import load_dataset, DatasetDict # Import DatasetDict here
import random
import torch

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.25.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.7.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)

# Load the dataset 'credit_card_qa'

In [2]:
import pandas as pd

path = '/content/credit_card_qa.csv'
df = pd.read_csv(path)
df.head()

,complaint,relevant_policy,policy_category,resolution,validity
0,"Dana Wu, using card ending 0044, purchased $12...","You will earn 4% Cash Back on the first $25,00...",Cashback - 4%,Apply missing 4% cashback for the eligible gro...,Valid: Purchase was at an eligible merchant an...
1,Dana Wu is asking why she didn't get 4% cashba...,"You will earn 4% Cash Back on the first $25,00...",Cashback - 4%,Explain that wholesale clubs are often not cla...,Invalid: Merchant not classified as eligible g...
2,Dana Wu purchased $50 worth of electronics alo...,Some merchants may sell these products/service...,Cashback - 4%,Explain that only the grocery portion of the p...,Invalid: Non-food items purchased at a grocery...
3,Dana Wu's monthly electricity bill of $80 is a...,Recurring Bill Payments are payments made on a...,Cashback - 4%,Apply missing 4% cashback for the recurring el...,Valid: Eligible recurring utility bill payment...
4,Dana Wu's $300 car loan payment is automatical...,Recurring Bill Payments are payments made on a...,Cashback - 4%,Explain that loan payments are not typically c...,Invalid: Loan payments are not eligible recurr...

In [9]:
from sklearn.model_selection import train_test_split

# Keep only the columns needed
df = df[['complaint', 'policy_category', 'resolution']].dropna().reset_index(drop=True)

# Sample 60 records for fine-tuning
train_df = df.sample(n=60, random_state=42).reset_index(drop=True)

# Remaining records (optional holdout view)
remaining_df = df.drop(train_df.index, errors='ignore').reset_index(drop=True)

print("Full dataset shape:", df.shape)
print("Fine-tuning sample shape:", train_df.shape)
print("Remaining records shape:", remaining_df.shape)

train_df.head()

Full dataset shape: (80, 3)
Fine-tuning sample shape: (60, 3)
Remaining records shape: (20, 3)

,complaint,policy_category,resolution
0,Bob Kim paid his $99 annual fee for his card e...,Cashback - Exclusions,Explanation provided to user that annual fees ...
1,"Dana Wu, using card ending 0044, purchased $12...",Cashback - 4%,Apply missing 4% cashback for the eligible gro...
2,Bob Kim is frustrated because he didn't receiv...,Cashback - Exclusions,Explanation provided to user that cash advance...
3,Bob Kim used his card ending in 0022 to pay $1...,Cashback - Exclusions,Explanation provided to user that government p...
4,Dana Wu is complaining that her 4% cashback wa...,Cashback - 4%,Explain that cashback is earned on *net* purch...

In [10]:
from IPython.display import Markdown
display(Markdown(str(train_df[:5])))

                                           complaint        policy_category  \
0  Bob Kim paid his $99 annual fee for his card e...  Cashback - Exclusions
1  Dana Wu, using card ending 0044, purchased $12...          Cashback - 4%
2  Bob Kim is frustrated because he didn't receiv...  Cashback - Exclusions
3  Bob Kim used his card ending in 0022 to pay $1...  Cashback - Exclusions
4  Dana Wu is complaining that her 4% cashback wa...          Cashback - 4%

                                          resolution
0  Explanation provided to user that annual fees ...
1  Apply missing 4% cashback for the eligible gro...
2  Explanation provided to user that cash advance...
3  Explanation provided to user that government p...
4  Explain that cashback is earned on *net* purch...

# Load the pre-trained language model and tokenizer

**For model 1:** It will take complaint as the input and predict policy_category.

In [14]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer
from datasets import Dataset

model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Build label mapping for policy_category
policy_labels = sorted(df["policy_category"].unique())
id2label_policy = {i: label for i, label in enumerate(policy_labels)}
label2id_policy = {label: i for i, label in id2label_policy.items()}

# Encode labels in the 60-record fine-tuning set
train_df_model1 = train_df[["complaint", "policy_category"]].copy()
train_df_model1["label"] = train_df_model1["policy_category"].map(label2id_policy)

# Convert to Hugging Face Dataset
ds_train_model1 = Dataset.from_pandas(train_df_model1[["complaint", "label"]])

# Load model with correct number of labels
model_1 = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=len(policy_labels),
    id2label=id2label_policy,
    label2id=label2id_policy
)

def preprocess_function_model1(examples):
    tokenized_inputs = tokenizer(
        examples["complaint"],
        truncation=True,
        padding="max_length",
        max_length=128
    )
    tokenized_inputs["labels"] = examples["label"]
    return tokenized_inputs

tokenized_train_model1 = ds_train_model1.map(preprocess_function_model1, batched=True)

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Map:   0%|          | 0/60 [00:00<?, ? examples/s]

In [15]:
# Print layer names
for name, param in model_1.named_parameters():
    print(name)

distilbert.embeddings.word_embeddings.weight
distilbert.embeddings.position_embeddings.weight
distilbert.embeddings.LayerNorm.weight
distilbert.embeddings.LayerNorm.bias
distilbert.transformer.layer.0.attention.q_lin.weight
distilbert.transformer.layer.0.attention.q_lin.bias
distilbert.transformer.layer.0.attention.k_lin.weight
distilbert.transformer.layer.0.attention.k_lin.bias
distilbert.transformer.layer.0.attention.v_lin.weight
distilbert.transformer.layer.0.attention.v_lin.bias
distilbert.transformer.layer.0.attention.out_lin.weight
distilbert.transformer.layer.0.attention.out_lin.bias
distilbert.transformer.layer.0.sa_layer_norm.weight
distilbert.transformer.layer.0.sa_layer_norm.bias
distilbert.transformer.layer.0.ffn.lin1.weight
distilbert.transformer.layer.0.ffn.lin1.bias
distilbert.transformer.layer.0.ffn.lin2.weight
distilbert.transformer.layer.0.ffn.lin2.bias
distilbert.transformer.layer.0.output_layer_norm.weight
distilbert.transformer.layer.0.output_layer_norm.bias
distilbert.transformer.layer.1.attention.q_lin.weight
distilbert.transformer.layer.1.attention.q_lin.bias
distilbert.transformer.layer.1.attention.k_lin.weight
distilbert.transformer.layer.1.attention.k_lin.bias
distilbert.transformer.layer.1.attention.v_lin.weight
distilbert.transformer.layer.1.attention.v_lin.bias
distilbert.transformer.layer.1.attention.out_lin.weight
distilbert.transformer.layer.1.attention.out_lin.bias
distilbert.transformer.layer.1.sa_layer_norm.weight
distilbert.transformer.layer.1.sa_layer_norm.bias
distilbert.transformer.layer.1.ffn.lin1.weight
distilbert.transformer.layer.1.ffn.lin1.bias
distilbert.transformer.layer.1.ffn.lin2.weight
distilbert.transformer.layer.1.ffn.lin2.bias
distilbert.transformer.layer.1.output_layer_norm.weight
distilbert.transformer.layer.1.output_layer_norm.bias
distilbert.transformer.layer.2.attention.q_lin.weight
distilbert.transformer.layer.2.attention.q_lin.bias
distilbert.transformer.layer.2.attention.k_lin.weight
distilbert.transformer.layer.2.attention.k_lin.bias
distilbert.transformer.layer.2.attention.v_lin.weight
distilbert.transformer.layer.2.attention.v_lin.bias
distilbert.transformer.layer.2.attention.out_lin.weight
distilbert.transformer.layer.2.attention.out_lin.bias
distilbert.transformer.layer.2.sa_layer_norm.weight
distilbert.transformer.layer.2.sa_layer_norm.bias
distilbert.transformer.layer.2.ffn.lin1.weight
distilbert.transformer.layer.2.ffn.lin1.bias
distilbert.transformer.layer.2.ffn.lin2.weight
distilbert.transformer.layer.2.ffn.lin2.bias
distilbert.transformer.layer.2.output_layer_norm.weight
distilbert.transformer.layer.2.output_layer_norm.bias
distilbert.transformer.layer.3.attention.q_lin.weight
distilbert.transformer.layer.3.attention.q_lin.bias
distilbert.transformer.layer.3.attention.k_lin.weight
distilbert.transformer.layer.3.attention.k_lin.bias
distilbert.transformer.layer.3.attention.v_lin.weight
distilbert.transformer.layer.3.attention.v_lin.bias
distilbert.transformer.layer.3.attention.out_lin.weight
distilbert.transformer.layer.3.attention.out_lin.bias
distilbert.transformer.layer.3.sa_layer_norm.weight
distilbert.transformer.layer.3.sa_layer_norm.bias
distilbert.transformer.layer.3.ffn.lin1.weight
distilbert.transformer.layer.3.ffn.lin1.bias
distilbert.transformer.layer.3.ffn.lin2.weight
distilbert.transformer.layer.3.ffn.lin2.bias
distilbert.transformer.layer.3.output_layer_norm.weight
distilbert.transformer.layer.3.output_layer_norm.bias
distilbert.transformer.layer.4.attention.q_lin.weight
distilbert.transformer.layer.4.attention.q_lin.bias
distilbert.transformer.layer.4.attention.k_lin.weight
distilbert.transformer.layer.4.attention.k_lin.bias
distilbert.transformer.layer.4.attention.v_lin.weight
distilbert.transformer.layer.4.attention.v_lin.bias
distilbert.transformer.layer.4.attention.out_lin.weight
distilbert.transformer.layer.4.attention.out_lin.bias
distilbert.transformer.layer.4.sa_layer_norm.weight
distilbert.transformer.layer.4.sa_layer_norm.bias
distilbert.transformer.layer.4.ffn.lin1.weight
distilbert.transformer.layer.4.ffn.lin1.bias
distilbert.transformer.layer.4.ffn.lin2.weight
distilbert.transformer.layer.4.ffn.lin2.bias
distilbert.transformer.layer.4.output_layer_norm.weight
distilbert.transformer.layer.4.output_layer_norm.bias
distilbert.transformer.layer.5.attention.q_lin.weight
distilbert.transformer.layer.5.attention.q_lin.bias
distilbert.transformer.layer.5.attention.k_lin.weight
distilbert.transformer.layer.5.attention.k_lin.bias
distilbert.transformer.layer.5.attention.v_lin.weight
distilbert.transformer.layer.5.attention.v_lin.bias
distilbert.transformer.layer.5.attention.out_lin.weight
distilbert.transformer.layer.5.attention.out_lin.bias
distilbert.transformer.layer.5.sa_layer_norm.weight
distilbert.transformer.layer.5.sa_layer_norm.bias
distilbert.transformer.layer.5.ffn.lin1.weight
distilbert.transformer.layer.5.ffn.lin1.bias
distilbert.transformer.layer.5.ffn.lin2.weight
distilbert.transformer.layer.5.ffn.lin2.bias
distilbert.transformer.layer.5.output_layer_norm.weight
distilbert.transformer.layer.5.output_layer_norm.bias
pre_classifier.weight
pre_classifier.bias
classifier.weight
classifier.bias

In [16]:
# Calculate the total number of parameters
total_params = sum(p.numel() for p in model_1.parameters())

# Print the result
print(f"Total number of parameters: {total_params}")

Total number of parameters: 66969621

Fine Tune the model_1

In [20]:
from transformers import TrainingArguments, Trainer, DataCollatorWithPadding

training_args_model1 = TrainingArguments(
    output_dir="./fine_tuned_policy_category_model",
    per_device_train_batch_size=4,
    num_train_epochs=5,
    logging_steps=5,
    report_to="none",
    learning_rate=2e-5,
    weight_decay=0.01,
    warmup_steps=10,
    save_strategy="epoch",
    eval_strategy="no"
)

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

trainer_model1 = Trainer(
    model=model_1,
    args=training_args_model1,
    train_dataset=tokenized_train_model1,
    data_collator=data_collator
)

trainer_model1.train()

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=75, training_loss=1.8463574600219728, metrics={'train_runtime': 187.879, 'train_samples_per_second': 1.597, 'train_steps_per_second': 0.399, 'total_flos': 9938421273600.0, 'train_loss': 1.8463574600219728, 'epoch': 5.0})

In [21]:
# Save the fine-tuned model_1 and tokenizer
save_path_model1 = "./saved_model1_policy_category"

trainer_model1.save_model(save_path_model1)
tokenizer.save_pretrained(save_path_model1)

print(f"Model 1 saved to: {save_path_model1}")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model 1 saved to: ./saved_model1_policy_category

# Test the model_1

In [22]:
from datasets import Dataset
from sklearn.metrics import accuracy_score, classification_report
import numpy as np

# Prepare the full dataset for evaluation
eval_df_model1 = df[["complaint", "policy_category"]].copy()
eval_df_model1["label"] = eval_df_model1["policy_category"].map(label2id_policy)

ds_eval_model1 = Dataset.from_pandas(eval_df_model1[["complaint", "label"]])

def preprocess_function_model1_eval(examples):
    tokenized_inputs = tokenizer(
        examples["complaint"],
        truncation=True,
        max_length=128
    )
    tokenized_inputs["labels"] = examples["label"]
    return tokenized_inputs

tokenized_eval_model1 = ds_eval_model1.map(preprocess_function_model1_eval, batched=True)

# Run predictions
pred_output_model1 = trainer_model1.predict(tokenized_eval_model1)

# Convert logits to predicted class IDs
y_pred_ids = np.argmax(pred_output_model1.predictions, axis=1)
y_true_ids = pred_output_model1.label_ids

# Convert IDs back to label names
y_pred_labels = [id2label_policy[i] for i in y_pred_ids]
y_true_labels = [id2label_policy[i] for i in y_true_ids]

# Metrics
acc_model1 = accuracy_score(y_true_labels, y_pred_labels)

print("Model 1 Accuracy on full dataset:", acc_model1)
print("\nClassification Report for Model 1:\n")
print(classification_report(y_true_labels, y_pred_labels))

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Model 1 Accuracy on full dataset: 0.625

Classification Report for Model 1:

                                           precision    recall  f1-score   support

                                 Cashback       0.00      0.00      0.00         1
                  Cashback - 1% Groceries       0.00      0.00      0.00         1
                            Cashback - 2%       0.00      0.00      0.00         3
                        Cashback - 2% Gas       0.00      0.00      0.00         2
                            Cashback - 4%       0.56      1.00      0.71        20
                   Cashback - Calculation       0.00      0.00      0.00         1
           Cashback - Eligible Categories       0.00      0.00      0.00         2
                    Cashback - Exclusions       0.33      1.00      0.50         7
                    Cashback - Expiration       0.00      0.00      0.00         1
          Cashback - Foreign Transactions       0.00      0.00      0.00         1
              Cashback - Posting Timeline       0.00      0.00      0.00         1
                    Cashback - Redemption       0.00      0.00      0.00         2
                      Contact Information       0.00      0.00      0.00         2
            Contact Information - Banking       0.00      0.00      0.00         2
          Contact Information - Concierge       0.00      0.00      0.00         2
 Contact Information - Emergency Services       0.00      0.00      0.00         2
          Contact Information - Insurance       1.00      0.60      0.75         5
Contact Information - Protection Services       0.00      0.00      0.00         3
          Miscellaneous - Program Changes       0.00      0.00      0.00         1
      Miscellaneous - Program Termination       0.00      0.00      0.00         1
                        Purchase Security       1.00      1.00      1.00        20

                                 accuracy                           0.62        80
                                macro avg       0.14      0.17      0.14        80
                             weighted avg       0.48      0.62      0.52        80

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Train the model_2

**For model 2:** It will take complaint as the input and predict resolution.

In [23]:
from transformers import AutoModelForSequenceClassification
from datasets import Dataset

# Build label mapping for resolution
resolution_labels = sorted(df["resolution"].unique())
id2label_resolution = {i: label for i, label in enumerate(resolution_labels)}
label2id_resolution = {label: i for i, label in id2label_resolution.items()}

# Encode labels in the 60-record fine-tuning set
train_df_model2 = train_df[["complaint", "resolution"]].copy()
train_df_model2["label"] = train_df_model2["resolution"].map(label2id_resolution)

# Convert to Hugging Face Dataset
ds_train_model2 = Dataset.from_pandas(train_df_model2[["complaint", "label"]])

# Load model_2
model_2 = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=len(resolution_labels),
    id2label=id2label_resolution,
    label2id=label2id_resolution
)

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [24]:
def preprocess_function_model2(examples):
    tokenized_inputs = tokenizer(
        examples["complaint"],
        truncation=True,
        max_length=128
    )
    tokenized_inputs["labels"] = examples["label"]
    return tokenized_inputs

tokenized_train_model2 = ds_train_model2.map(preprocess_function_model2, batched=True)

Map:   0%|          | 0/60 [00:00<?, ? examples/s]

In [26]:
from transformers import TrainingArguments, Trainer, DataCollatorWithPadding

training_args_model2 = TrainingArguments(
    output_dir="./fine_tuned_resolution_model",
    per_device_train_batch_size=4,
    num_train_epochs=5,
    logging_steps=5,
    report_to="none",
    learning_rate=2e-5,
    weight_decay=0.01,
    warmup_steps=10,
    save_strategy="epoch",
    eval_strategy="no"
)

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

trainer_model2 = Trainer(
    model=model_2,
    args=training_args_model2,
    train_dataset=tokenized_train_model2,
    data_collator=data_collator
)

trainer_model2.train()

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=75, training_loss=4.280822168986003, metrics={'train_runtime': 133.7547, 'train_samples_per_second': 2.243, 'train_steps_per_second': 0.561, 'total_flos': 4725547188480.0, 'train_loss': 4.280822168986003, 'epoch': 5.0})

In [27]:
save_path_model2 = "./saved_model2_resolution"

trainer_model2.save_model(save_path_model2)
tokenizer.save_pretrained(save_path_model2)

print(f"Model 2 saved to: {save_path_model2}")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model 2 saved to: ./saved_model2_resolution

In [28]:
from sklearn.metrics import accuracy_score, classification_report
import numpy as np

# Prepare the full dataset for evaluation
eval_df_model2 = df[["complaint", "resolution"]].copy()
eval_df_model2["label"] = eval_df_model2["resolution"].map(label2id_resolution)

ds_eval_model2 = Dataset.from_pandas(eval_df_model2[["complaint", "label"]])

def preprocess_function_model2_eval(examples):
    tokenized_inputs = tokenizer(
        examples["complaint"],
        truncation=True,
        max_length=128
    )
    tokenized_inputs["labels"] = examples["label"]
    return tokenized_inputs

tokenized_eval_model2 = ds_eval_model2.map(preprocess_function_model2_eval, batched=True)

# Predict
pred_output_model2 = trainer_model2.predict(tokenized_eval_model2)

# Convert logits to predicted IDs
y_pred_ids_model2 = np.argmax(pred_output_model2.predictions, axis=1)
y_true_ids_model2 = pred_output_model2.label_ids

# Convert IDs back to label names
y_pred_labels_model2 = [id2label_resolution[i] for i in y_pred_ids_model2]
y_true_labels_model2 = [id2label_resolution[i] for i in y_true_ids_model2]

# Metrics
acc_model2 = accuracy_score(y_true_labels_model2, y_pred_labels_model2)

print("Model 2 Accuracy on full dataset:", acc_model2)
print("\nClassification Report for Model 2:\n")
print(classification_report(y_true_labels_model2, y_pred_labels_model2))

Map:   0%|          | 0/80 [00:00<?, ? examples/s]

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Model 2 Accuracy on full dataset: 0.1375

Classification Report for Model 2:

                                                                                                                                                                                                                                                                                                                                    precision    recall  f1-score   support

                                                                                                                                                                      Apologize for the dissatisfaction and offer to have another concierge agent assist with more personalized recommendations. Review concierge service quality.       0.33      1.00      0.50         1
                                                                                                                                                                                                                                                                      Apply missing 4% cashback for the eligible grocery purchase.       1.00      1.00      1.00         2
                                                                                                                                                                                    Apply missing 4% cashback for the recurring electricity bill payments, as utility bills generally fall under eligible recurring bill payments.       0.00      0.00      0.00         1
                                                                                                                                                                                       Apply missing 4% cashback for the recurring home security system payment, as it falls under eligible membership/subscription-like services.       0.14      1.00      0.25         1
                                                                                                                                                                                                                                                                  Apply missing 4% cashback for the recurring phone bill payments.       0.00      0.00      0.00         1
                                                                                                                                                                                                                                                        Apply missing 4% cashback for the recurring software subscription payment.       0.00      0.00      0.00         1
                                                                                                                                                                             Clarify that this line is for credit card-related insurance claims and not general home insurance. Advise him to contact his home insurance provider.       0.00      0.00      0.00         1
                                                                                                                                                                                                                                      Complaint routed to cashback department for investigation as Bob claims he is within limits.       0.00      0.00      0.00         1
                                                                                                                                                                                                                   Complaint routed to cashback for investigation and adjustment, as Bob's spending is within the eligible limits.       0.00      0.00      0.00         1
                                                                                                                                                                                                                             Complaint routed to cashback for investigation of the incorrect cashback rate applied and adjustment.       0.12      1.00      0.22         1
                                                                                                                                                                                                        Escalate to investigate delays in emergency card replacement delivery and communicate realistic timelines to the customer.       0.00      0.00      0.00         1
                                                                                                                                                                                                                                                                                       Explain ineligibility due to card mismatch.       0.00      0.00      0.00         1
                                                                                      Explain that 1-900 numbers are premium rate services and clarify how charges apply. Policy should be updated to explicitly state that calls to 1-900 numbers are charged and provide estimated rates or advise checking with phone provider.       0.00      0.00      0.00         1
Explain that ABC Credit Card Protection primarily covers issues related to the credit card itself (fraud, loss, theft of card) and not general personal property like phones, unless specifically covered by an associated card benefit (e.g., mobile phone insurance benefit). Advise contacting his personal property insurance.       0.00      0.00      0.00         1
                                                                                                                                                                                 Explain that ATM withdrawals and associated fees are considered cash advances, not eligible purchases, and therefore do not qualify for cashback.       0.00      0.00      0.00         1
                                                                                                             Explain that Purchase Security applies to 'Insured Items' purchased with the card, not to cash withdrawals or other non-purchase transactions. Advise to report the theft to local authorities if she hasn't already.       0.00      0.00      0.00         1
                                                                                                                                                                                         Explain that Purchase Security applies to items purchased by the cardholder using their eligible card, not to gifts received from others.       0.00      0.00      0.00         1
                                                                                                                                                                                               Explain that Purchase Security is only applicable to purchases made with the eligible card (4000 1000 0000 0055) by the cardholder.       0.00      0.00      0.00         1
                                                                                                                                               Explain that Purchase Security only applies to eligible items purchased after the card was issued and the policy was in effect. The purchase predates the card and policy coverage.       0.00      0.00      0.00         1
                                                                                                                               Explain that Purchase Security typically covers physical 'Insured Items' and not intangible services or business failures. Advise to contact the service provider or file a dispute if appropriate.       0.17      1.00      0.29         1
                                                                                                                                                                                                        Explain that VAC is for emergencies only and provide the correct number for balance inquiries (TeleABC Telephone Banking).       0.00      0.00      0.00         1
                                                                                                                                                 Explain that cashback is earned on *net* purchases; when items are returned, the corresponding cashback is typically reversed as the purchase is no longer considered 'eligible'.       0.04      1.00      0.08         1
                                                                                                                                                      Explain that charitable donations, even if recurring, are typically excluded from cashback programs and do not fall under the eligible 'recurring bill payments' categories.       0.00      0.00      0.00         1
                                                                                                                                                                                               Explain that coverage ceased on 05/15/2024 when the account was no longer in Good Standing, which was prior to the damage incident.       0.00      0.00      0.00         1
                                                                                                                                                                                                                                   Explain that coverage ceased when eligibility ended on 05/01/2024, prior to the theft incident.       0.00      0.00      0.00         1
                                                                                                                                                               Explain that food delivery services, when purchasing from restaurants, are classified as dining/restaurant, not grocery, and thus are not eligible for 4% cashback.       0.00      0.00      0.00         1
                                                                                                                                                                                     Explain that loan payments are not typically classified as eligible 'recurring bill payments' under the specified categories for 4% cashback.       0.00      0.00      0.00         1
                                                                                                                                                                Explain that medical co-pays, while potentially regular, are not typically classified as eligible 'recurring bill payments' under the policy's defined categories.       0.00      0.00      0.00         1
                                                                                                                                                                                     Explain that office supply stores are not eligible categories (Grocery Stores & Supermarkets or Recurring Bill Payments) for the 4% cashback.       0.00      0.00      0.00         1
                                                                                                                                               Explain that only the grocery portion of the purchase qualifies for cashback if the merchant codes differentiate categories within the store; electronics typically do not qualify.       0.00      0.00      0.00         1
                                                                                                                                                                                                  Explain that property tax payments are generally not classified as eligible 'recurring bill payments' for this cashback program.       0.00      0.00      0.00         1
                                                                                                                                                                                                           Explain that purchase security typically covers damage or theft, not simply loss. Advise to review full policy details.       0.00      0.00      0.00         1
                                                                                                                                                             Explain that telephone banking services are typically for account management and direct him to the appropriate department or online portal for mortgage applications.       0.00      0.00      0.00         1
                                                                Explain that the 2% cashback is specifically limited to eligible gas purchases and not a general cashback on all spending. Policy could be updated to explicitly state other purchase categories do not qualify for 2% cashback if it's a common misunderstanding.       0.00      0.00      0.00         1
                                                                                                           Explain that the 4% cashback is capped at the first $25,000 spent annually *across both eligible categories combined*, and purchases beyond this limit are not eligible. In this case, she exceeded the combined limit.       0.00      0.00      0.00         1
                                                                                                                                                                                                                                   Explain that the 4% cashback is only for *recurring* bill payments, not one-time service bills.       0.00      0.00      0.00         1
                                                                                                                                                                                              Explain that the item was purchased after cardmember eligibility for coverage had ended, making it ineligible for Purchase Security.       0.00      0.00      0.00         1
                                                                                                                                                                                               Explain that the item was purchased when the account was not in Good Standing, and thus coverage had ended at the time of purchase.       0.00      0.00      0.00         1
                                                        Explain that the number is for Canada & U.S. only and provide the correct international contact method or collect call number for emergency medical assistance abroad, if available. Policy should clarify international contact details for emergency medical assistance.       0.00      0.00      0.00         1
                                                                                                                                                                   Explain that the policy clearly states 'date of purchase' for the 90-day coverage period, not delivery date. The item is therefore outside the coverage window.       0.00      0.00      0.00         1
                                                                                                                                                                                                                             Explain that the service is specifically for ABC Credit Cards and advise him to contact his own bank.       0.07      1.00      0.12         1
                                                                                                                                                                  Explain that this was a one-time manual purchase, not an automatically billed recurring payment, and it does not fall under eligible categories for 4% cashback.       0.00      0.00      0.00         1
                                                                                                                                                                                  Explain that transactions made outside of the domestic market may be classified differently by Visa or excluded from specific cashback programs.       0.00      0.00      0.00         1
                                                                                                                                                                                        Explain that travel emergency medical insurance typically excludes pre-existing conditions and advise to check policy terms for specifics.       0.00      0.00      0.00         1
                                                                                                                                                         Explain that while concierge services assist with bookings, extreme or last-minute requests may be subject to availability and feasibility. Manage customer expectations.       0.00      0.00      0.00         1
                                                                                                                                 Explain that wholesale clubs are often not classified as Grocery Stores & Supermarkets (Merchant Code 5411) by Visa, even if they sell groceries, and are therefore not eligible for 4% cashback.       0.00      0.00      0.00         1
                                                    Explain the distinction between travel medical emergencies and other card-related insurance claims handled by the same number, and clarify which prompts or options to select. Policy should be updated to clearly define the services available under a single shared number.       0.00      0.00      0.00         1
                                                                                                                                                                                                                     Explain the limitations of phone service for specific administrative tasks and direct to online/mail options.       0.00      0.00      0.00         1
                                    Explanation provided regarding the current policy's allowance for changes. Policy should be updated: 'Ensure all marketing materials clearly state that program terms are subject to change and may not be guaranteed for the lifetime of the card, unless explicitly stated with conditions.'       0.00      0.00      0.00         1
                                                                                                                                                                                                                        Explanation provided that the theft occurred outside the 90-day coverage period from the date of purchase.       0.00      0.00      0.00         1
                                                                                                                                                                                                                                           Explanation provided to user that a minimum of $20 is required for cashback redemption.       0.00      0.00      0.00         1
                                                                                                                                                                                                                           Explanation provided to user that accumulated cashback is forfeited upon account closure as per policy.       0.00      0.00      0.00         1
                                                                                                                                                                                                                                             Explanation provided to user that annual fees are excluded from cashback eligibility.       0.00      0.00      0.00         1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

The first model, which predicts policy_category from the complaint text, achieved an accuracy of 62.5% on the full dataset, suggesting that fine-tuning DistilBERT was reasonably effective for category classification, especially for broader and more repeated classes such as Purchase Security and Cashback - 4%. However, the classification report also shows that performance was uneven across labels. Many minority classes had precision, recall, and F1-scores of 0.00, indicating that the model largely failed to generalize to rare categories. This is consistent with the small fine-tuning sample of only 60 records and the highly imbalanced label distribution.

The second model, which predicts resolution from the complaint text, performed much worse, with an accuracy of only 13.75%. This result indicates that fine-tuning was not very successful for this task. The main reason is that resolution appears to be much more detailed and fine-grained than policy_category, with many unique or near-unique target responses. In effect, this makes the problem much harder, because the model is being asked to choose among many long, highly specific labels from very limited training data. DistilBERT sequence classification is generally better suited to a small set of repeated classes than to highly varied output texts.

The comparison shows that fine-tuning works better when the target labels are structured, limited, and repeated, as in the policy_category task. It works poorly when the target labels are long, numerous, and highly specific, as in the resolution task. A key insight from this experiment is that model performance depends not only on the model architecture, but also on how the prediction task is formulated. For the resolution task, a generative model such as DistilGPT2, or a reformulation into broader resolution groups, would likely be more appropriate than direct multi-class classification. Finally, since evaluation was conducted on the full dataset, including the 60 training examples, the reported scores may be somewhat optimistic and should not be interpreted as pure out-of-sample performance.